### ISSUE TITLE
insert_records_of_one_device 数据行上限问题

### ISSUE THREAD

**Issue by MatteoSwift** [eedalong/iotdb-client-csharp#29]
insert_records_of_one_device / insert_records_of_one_device_sorted 

测试数据 400列 86400行，无法写入，等待数十分钟无返回结果
csv数据，去掉时间列，文件大约220MB

改进建议：如果一次性不能支持这个量级，希望能在接口内部分批次发送，比如3600行发送一次，而不是让使用者分批次调用接口

测试结果：每3600行(1小时)数据，调用一次insert_records_of_one_device_sorted可以正常执行。

**Comment by eedalong** [comment]
@lausannel  在insert_records_of_one_device中支持下切片上传
