### ISSUE TITLE
打开Session时异常Thrift.Transport.TTransportException

### ISSUE THREAD

**Issue by MatteoSwift** [eedalong/iotdb-client-csharp#7]
Exception thrown: 'Thrift.Transport.TTransportException' in Thrift.dll
nodename nor servname provided, or not known

调用Session.open函数时，如果host指定为非localhost，则引发上述异常。
var session_local = new Session("127.0.0.1",6667); // iotdb数据库服务与测试同机，正常
var session_remote=  new Session("192.168.0.29",6667); // iotdb数据库服务与测试不同机，异常

**Comment by eedalong** [comment]
好的好的，该问题已经解决，正在发布新的客户端，稍等！

**Comment by eedalong** [comment]
新的客户端版本已经发布，请重新安装最新的客户端，[具体可见这里](https://github.com/eedalong/iotdb-client-csharp/packages/727613)。
